// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZnUWtCrJKd11O56Y9IY8_2SQo-5ksVRw',
    appId: '1:303549200903:web:44a0f1086edf3d92f308a2',
    messagingSenderId: '303549200903',
    projectId: 'fluttersignin-23daf',
    authDomain: 'fluttersignin-23daf.firebaseapp.com',
    storageBucket: 'fluttersignin-23daf.appspot.com',
    measurementId: 'G-TF52682Q3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYxzxCPhPC_ESYkIFM_58Tg1JoxZTl87A',
    appId: '1:303549200903:android:dd2b85963a146d33f308a2',
    messagingSenderId: '303549200903',
    projectId: 'fluttersignin-23daf',
    storageBucket: 'fluttersignin-23daf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8DymNeCUX1SoWUXmndrLidC3YbKD1sBI',
    appId: '1:303549200903:ios:236d6b3d8935898df308a2',
    messagingSenderId: '303549200903',
    projectId: 'fluttersignin-23daf',
    storageBucket: 'fluttersignin-23daf.appspot.com',
    iosBundleId: 'com.example.flutterfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8DymNeCUX1SoWUXmndrLidC3YbKD1sBI',
    appId: '1:303549200903:ios:860734423586f62af308a2',
    messagingSenderId: '303549200903',
    projectId: 'fluttersignin-23daf',
    storageBucket: 'fluttersignin-23daf.appspot.com',
    iosBundleId: 'com.example.flutterfirebase.RunnerTests',
  );
}
